---
- name: Get data from nodes
  gather_facts: true
  hosts: worker
  tasks:
    - name: Get data from nodes
      fetch:
        src: "{{wd}}/{{data_file}}"
        dest: "{{dest}}/{{data_file}}"
        flat: yes
    - debug:
        msg: "Output files have been written to {{dest}}/{{data_file}}"
