# settings for vagrant setup
[master]
memory=2048
cpu=1

[worker]
memory=2048
cpu=1
total=1

[bot]
memory=1024
cpu=1
total=1

# settings for python benchmark
[benchmark]
WORLD='CastleLividus'
playerModel=['walk', 'pvp']
DENSITY=[3, 5, 10]
RADIUS=[15000, 5000]
# REDSTONE=['world 1', 'world 2']
PLAYERS=[500, 1000]
# PVE_Mobs=['zombie', 'polar_bear', 'witch', 'elder dragon']
