# settings for vagrant setup
[master]
memory=2048
cpu=1

[worker]
memory=4096
cpu=2
total=1

[bot]
memory=4096
cpu=1
total=1

# settings for python benchmark
[benchmark]
world='CastleLividus'
playerModel='build'
density=1
radius=500
# REDSTONE=['world 1', 'world 2']
players=5 # this is per node
pve_mob='polar_bear' # will result into ['zombie', 'polar_bear']
# total duration of benchmark = 30 secs + (joinDelaySecs * playerCount/bot_total) + 3 minute
joinDelaySecs=5
