# settings for vagrant setup
[master]
memory=2048
cpu=1

[worker]
memory=4096
cpu=2
total=1

[bot]
memory=2048
cpu=1
total=1

# settings for python benchmark
[benchmark]
world='CastleLividus'
playerModel=['walk']
density=[5]
radius=[5000]
# REDSTONE=['world 1', 'world 2']
players=[5]
pve_mob='zombie' # will result into ['zombie', 'polar_bear']
# total duration of benchmark = 30 secs + (joinDelaySecs * playerCount/bot_total) + 3 minute
joinDelaySecs=5
