# settings for vagrant setup
[master]
memory=2048
cpu=1

[worker]
memory=2048
cpu=2
total=1

[bot]
memory=2048
cpu=1
total=1

# settings for python benchmark
[benchmark]
world='WorldOfWorlds'
playerModel=['walk']
density=[2]
radius=[5000]
# REDSTONE=['world 1', 'world 2']
players=[4]
# PVE_Mobs=['zombie', 'polar_bear', 'witch', 'elder dragon']
# total duration of benchmark = 30 secs + (joinDelaySecs * playerCount/bot_total) + 5 minute
joinDelaySecs=5
