# settings for vagrant setup
[master]
memory=1024
cpu=2

[worker]
memory=4096
cpu=1
total=1

[bot]
memory=2048
cpu=1
total=1

# settings for python benchmark
[benchmark]
world='CastleLividus'
playerModel='walk'
density=5
radius=10
# REDSTONE=['world 1', 'world 2']
players=10 # this is per node
pve_mob='polar_bear' # will result into ['zombie', 'polar_bear']
# total duration of benchmark = 30 secs + (joinDelaySecs * playerCount/bot_total) + 3 minute
joinDelaySecs=5
seed='None'
spawn=["100:220"]
