- name: Run worker
  hosts: all

  tasks:
    - name: Edit multipaper.yml file on worker
      shell: "nohup java -DbungeecordName={{ansible_hostname}} -DmultipaperMasterAddress={{master}}:35353 -jar multipaper-1.20.1-57.jar >/dev/null 2>&1 </dev/null &"
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Wait for template editing on worker
      pause:
        seconds: 30

    - name: Gracefully shutdown worker template editing
      command: pkill -SIGTERM -f "java -DbungeecordName={{ansible_hostname}} -DmultipaperMasterAddress={{master}}:35353 -jar multipaper-1.20.1-57.jar"
      ignore_errors: true

    - name: Edit eula.txt file
      command: sed -i 's/eula=false/eula=true/' eula.txt
      args:
        chdir: ~/worker

    - name: Generate more template files after accepting eula
      shell: nohup java -jar multipaper-1.20.1-57.jar >/dev/null 2>&1 </dev/null &
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Wait for template generation on worker
      pause:
        seconds: 45
    
    - name: Gracefull shutdown worker template generation
      command: pkill -SIGTERM -f "java -jar multipaper-1.20.1-57.jar"
      ignore_errors: true

    - name: Configure worker backend to work with velocity
      shell: |
        cat bukkit.yml | dasel put -r yaml -t int -o bukkit.yml -v -1 'settings.connection-throttle'
        cat config/paper-global.yml | dasel put -r yaml -t bool -o config/paper-global.yml -v false 'proxies.bungee-cord.online-mode'
        cat config/paper-global.yml | dasel put -r yaml -t bool -o config/paper-global.yml -v true 'proxies.velocity.enabled'
        cat config/paper-global.yml | dasel put -r yaml -t string -o config/paper-global.yml -v secret 'proxies.velocity.secret'
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Run multipaper worker node using jolokia
      shell: nohup java -javaagent:jolokia-agent-jvm-2.0.3-javaagent.jar -jar multipaper-1.20.1-57.jar </dev/null > "worker-{{inventory_hostname}}.log" &
      args:
        chdir: ~/worker
        executable: /bin/bash
