---
- hosts: all
  gather_facts: True
  environment:
    DURATION: "{{duration}}"
    MC_HOST: "{{mc_host}}"
    SPAWN_X: "{{spawn_x}}"
    SPAWN_Z: "{{spawn_z}}"
    SPAWN_Y: "{{spawn_y}}"
    BOX_WIDTH: "{{box_width}}"
    BOX_X: "{{box_x}}"
    BOX_Z: "{{box_z}}"
    BOTS_JOIN_DELAY: "{{bots_join_delay}}"
    BOTS_PER_NODE: "{{bots_per_node}}"
    RECORD: "{{record}}"
    HOSTNAME: "{{inventory_hostname}}"
    DENSITY: "{{density}}"
    MAX_RADIUS: "{{max_radius}}"
    WORKLOAD: "{{workload}}"
    WORLDNAME: "{{world_name}}"
  tasks:
    - name: Set game spawn location
      shell: source ~/.nvm/nvm.sh && node set_spawn.js
      args: 
        chdir: "{{ wd }}"
        executable: /bin/bash
      run_once: true # run once
      when: false
    
    - name: Run Minecraft bot
      shell: |
          bash -i << EOF
          nohup node master_bot.js > bot-{{ inventory_hostname }}.log 2>&1 </dev/null & 
          echo $! > bot-{{inventory_hostname}}.pid
          exit
          EOF
      args:
        chdir: "{{ wd }}"
        executable: /bin/bash
      environment:
        BOT_INDEX: "{{ groups['all'].index(inventory_hostname) }}" 
