---
- name: Deploy Minecraft WalkAround workload
  gather_facts: true
  hosts: all
  tasks:
    - debug:
        msg: "working directory is: {{wd}}"
    - file:
        path: "{{ wd }}"
        state: directory
    
    - name: Check if nvm is available
      shell: |
        source ~/.nvm/nvm.sh && nvm --version
      register: nvm_version
      #failed_when: nvm_version.rc != 0 and nvm_version.rc != 127
      when: false
      args:
        executable: /bin/bash
    
    - name: Install nvm
      shell: |
        if ! test -f ~/.nvm/nvm.sh
        then
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
        fi
    
    - name: Install node 18 and mineflayer, pathfinder, pve-mineflayer, construction-mineflayer
      shell: |
        source ~/.nvm/nvm.sh && nvm install 18 && npm install mineflayer && npm install mineflayer-pathfinder && npm install mineflayer-pvp       
      args:
        executable: /bin/bash
        chdir: "{{ wd }}"
    
    - name: Checkout RCON client
      git:
        repo: https://github.com/tehbeard/node-rcon.git
        dest: "{{wd}}/rcon"
    
    - name: Copy scripts
      copy:
        src: "{{item}}"
        dest: "{{wd}}"
      with_items: "{{scripts}}"
