---
- hosts: all
  gather_facts: True
  environment:
    DURATION: "{{duration}}"
    MC_HOST: "{{mc_host}}"
    SPAWN_X: "{{spawn_x}}"
    SPAWN_Y: "{{spawn_y}}"
    BOX_WIDTH: "{{box_width}}"
    BOX_X: "{{box_x}}"
    BOX_Z: "{{box_z}}"
    BOTS_JOIN_DELAY: "{{bots_join_delay}}"
    BOTS_PER_NODE: "{{bots_per_node}}"
  tasks:
    - name: Set game spawn location
      shell: source ~/.nvm/nvm.sh && node set_spawn.js
      args: 
        chdir: "{{ wd }}"
        executable: /bin/bash
      run_once: true # Only run on one machine
    
    - name: Run Minecraft bot
      shell: |
          bash -i << EOF
          nohup node walkaround_bot.js > bot-{{ inventory_hostname }}.log 2>&1 </dev/null & 
          echo $! > bot-{{inventory_hostname}}.pid
          exit
          EOF
      args:
        chdir: "{{ wd }}"
        executable: /bin/bash
      environment:
        BOT_INDEX: "{{ groups['all'].index(inventory_hostname) }}"

    - name: Run prismarine viewer
      when: false
      shell: |
        nohup node bot_viewer.js >/dev/null &
      args:
        chdir: "{{ wd }}"
        executable: /bin/bash
      run_once: true # Only run one bot viewer
