---
- name: Clean data from nodes
  gather_facts: true
  hosts: all
  tasks:
    - name: Find all CSV files in wd
      find:
        paths: "{{ wd }}"
        patterns: "*.csv"
        recurse: true
      register: csv_files

    - name: Remove data from nodes
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ csv_files.files }}"

    - name: Find all log files in wd
      find:
        paths: "{{ wd }}"
        patterns: "*.log"
        recurse: true
      register: log_files

    - name: Remove data from nodes
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ log_files.files }}"

