---
- name: Get data from nodes
  gather_facts: true
  hosts: all
  tasks:
    - name: Find all CSV files in wd
      find:
        paths: "{{ wd }}"
        patterns: "metrics-*.csv"
        recurse: true
      register: csv_files

    - name: Get csv files from all nodes
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ dest }}/{{ item.path | basename }}"
        flat: yes
      loop: "{{ csv_files.files }}"

- name: Get logs from worker nodes
  gather_facts: true
  hosts: all
  tasks:
    - name: Find all log files in worker directory
      find:
        paths: "~/worker/logs"
        patterns: "*.log"
        recurse: true
      register: log_files
      ignore_errors: true 

    - name: Get log files from worker nodes
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ dest }}/{{ansible_hostname}}-{{ item.path | basename }}"
        flat: yes
      loop: "{{ log_files.files }}"

    - name: Get worker bot position log file
      ansible.builtin.fetch:
        src: "{{ wd }}/logs/bots.log"
        dest: "{{ dest }}/{{ ansible_hostname }}-bots-pos.log"
        flat: yes
      ignore_errors: true

    - name: Find all log files in worker directory
      find:
        paths: "~/velocity/logs"
        patterns: "*.log"
        recurse: true
      register: master_log_files
      ignore_errors: true 

    - name: Get log files from master node
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ dest }}/master-{{ item.path | basename }}"
        flat: yes
      loop: "{{ master_log_files.files }}"

    - name: Get chunk log files from worker nodes
      ansible.builtin.fetch:
        src: "~/worker/chunk-logs.txt"
        dest: "{{ dest }}/{{ ansible_hostname }}-chunk-logs.txt"
        flat: yes
      ignore_errors: true
