- name: Run worker
  hosts: all

  tasks:
    - name: Edit multipaper.yml file on worker
      shell: | 
        nohup java -DbungeecordName={{ansible_hostname}} -DmultipaperMasterAddress={{master}}:35353 -jar multipaper-1.20.1-57.jar >worker1.log 2>&1 </dev/null &
        echo $! > template.pid
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Wait for template editing on worker to complete
      shell: |
        sleep 5
        while true; do
          COUNT=$( cat worker1.log | grep -c "You need to agree to the EULA" )
          if [[ $COUNT -ge 1 ]]; then
            exit
          fi
          sleep 1
        done
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Gracefully shutdown worker template editing
      shell: |
        kill -SIGKILL $(cat template.pid)
        rm worker1.log
      args:
        chdir: ~/worker
        executable: /bin/bash
    
    - name: Edit eula.txt file
      command: sed -i 's/eula=false/eula=true/' eula.txt
      args:
        chdir: ~/worker

    - name: Generate more template files after accepting eula
      shell: |
        nohup java -jar multipaper-1.20.1-57.jar >worker2.log 2>&1 </dev/null &
        echo $! > template.pid
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Wait for template generation on worker
      shell: |
        sleep 5
        while true; do
          COUNT=$( cat worker2.log | grep -c "Done" )
          if [[ $COUNT -ge 1 ]]; then
            exit
          fi
          sleep 1
        done
      args:
        chdir: ~/worker
        executable: /bin/bash
    
    - name: Gracefull shutdown worker template generation
      shell: |
        kill -SIGKILL -f $(cat template.pid)
        rm worker2.log
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Configure worker backend to work with velocity
      shell: |
        cat bukkit.yml | dasel put -r yaml -t int -o bukkit.yml -v -1 'settings.connection-throttle'
        cat config/paper-global.yml | dasel put -r yaml -t bool -o config/paper-global.yml -v false 'proxies.bungee-cord.online-mode'
        cat config/paper-global.yml | dasel put -r yaml -t bool -o config/paper-global.yml -v false 'proxies.velocity.enabled'
        cat config/paper-global.yml | dasel put -r yaml -t string -o config/paper-global.yml -v secret 'proxies.velocity.secret'
        cat spigot.yml | dasel put -r yaml -t bool -o spigot.yml -v true 'settings.bungeecord'
        cat pufferfish.yml | dasel put -r yaml -t bool -o pufferfish.yml -v true 'misc.disable-out-of-order-chat'
        cat spigot.yml | dasel put -r yaml -t string -o spigot.yml -v ./restart.sh 'settings.restart-script'
        cat spigot.yml | dasel put -r yaml -t int -o spigot.yml -v 120 'settings.timeout-time'
      args:
        chdir: ~/worker
        executable: /bin/bash

    - name: Ensure Skript script directory exists
      file:
        path: ~/worker/plugins/Skript/scripts/
        state: directory

    - name: Copy Skript auto-op script
      copy:
        dest: ~/worker/plugins/Skript/scripts/autop.sk
        content: |
          on join:
            message "Yardstick 2.0 Minecraft Benchmark"
            make console execute command "/op %player%"

    - name: Copy node restart on crash script
      copy:
        dest: ~/worker/restart.sh
        mode: '0755'
        content: |
          rm /tmp/worker_stdin
          mkfifo /tmp/worker_stdin
          nohup tail -f /dev/null > /tmp/worker_stdin &
          echo $! > tail_fifo.pid 
          nohup java -Xmx{{memory}}M -javaagent:jolokia-agent-jvm-2.0.3-javaagent.jar -jar multipaper-1.20.1-57.jar </tmp/worker_stdin > "worker-{{inventory_hostname}}.log" &
          echo $! > jolokia.pid


    - name: Run multipaper worker node using jolokia
      shell: |
        mkfifo /tmp/worker_stdin
        nohup tail -f /dev/null > /tmp/worker_stdin &
        echo $! > tail_fifo.pid 
        nohup java -Xmx{{memory}}M -javaagent:jolokia-agent-jvm-2.0.3-javaagent.jar -Dpaper.playerconnection.keepalive=300 -jar multipaper-1.20.1-57.jar </tmp/worker_stdin > "worker-{{inventory_hostname}}.log" &
        echo $! > jolokia.pid
      args:
        chdir: ~/worker
        executable: /bin/bash

