- name: Shutdown multipaper master
  hosts: all
  tasks:
    - name: Shutdown multipaper master
      shell: |
        kill -SIGKILL $(cat master.pid)
      ignore_errors: true
      args:
        executable: /bin/bash
        chdir: ~/velocity
