- name: Shutdown workers
  hosts: all

  tasks:
    - name: Shutdown nohup multipaper java jolokia worker
      command: pkill -SIGTERM -f "java -javaagent:jolokia-agent-jvm-2.0.3-javaagent.jar -jar multipaper-1.20.1-57.jar"
