---
- name: Start Telegraf
  gather_facts: true
  hosts: all

  tasks:
    - name: Find executable
      shell: |
        find -type f -executable -name telegraf
      register: find_telegraf
      args:
        chdir: "{{wd}}"
    
    - name: Run Telegraf
      shell:
        cmd: |
          nohup {{find_telegraf.stdout}} --config telegraf-{{inventory_hostname}}.conf --pidfile telegraf-{{inventory_hostname}}.pid &> telegraf.log &
      args:
        chdir: "{{wd}}"
        executable: /bin/bash

